# Generated by Django 4.1.1 on 2022-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_lostitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация для передачи'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/found_items', verbose_name='Изображение найденного предмета'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location2',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Вторая локация'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location3',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Третья локация'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/lost_items', verbose_name='Изображение потерянного предмета'),
        ),
    ]
