# Generated by Django 4.1.1 on 2022-09-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_founditem_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LostItem',
        ),
    ]
