# Generated by Django 4.1.1 on 2022-09-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_delete_lostitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вещи')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/found_items', verbose_name='Изображение найденного предмета')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('geotag', models.CharField(max_length=255, verbose_name='Место потери')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация для передачи')),
                ('is_lost', models.BooleanField(default=False, verbose_name='Является ли вещь потерянной')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Найденная вещь',
                'verbose_name_plural': 'Найденные вещи',
            },
        ),
        migrations.DeleteModel(
            name='FoundItem',
        ),
    ]
